- hosts: localhost
  become_method: su

  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "home/tokyaramen/.ssh/id_ed25519"

  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - node
  tasks:
    - name: Node list

      ansible.builtin.include_tasks: tasks/node.yml

    - name: NPM basic packages setup

      ansible.builtin.include_tasks: tasks/npm-packages.yml

    - name: SSH setup

      ansible.builtin.include_tasks: tasks/ssh.yml

    - name: Git setup

      ansible.builtin.include_tasks: tasks/git-setup.yml

    - name: Productivity-tools setup

      ansible.builtin.include_tasks: tasks/productivity.yml
    - name: Core-tools setup

      ansible.builtin.include_tasks: tasks/core-tools.yml

    - name: Cloning tmux plugin manager

      ansible.builtin.include_tasks: tasks/tpm.yml

    - name: Go setup

      ansible.builtin.include_tasks: tasks/go-setup.yml
