- hosts: localhost
  become_method: su
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
  tasks:
    - name: Change shell
      shell: chsh -s `which bash`
      tags:
        - zsh
