- hosts: localhost
  become_method: su
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME' )}}/.ssh/id_ed25519"
  tasks:
    - name: Ensure .ssh directory exists
      file:
        dest: "{{ dest_key | dirname }}"
        mode: 0700
        state: directory
      tags:
        - ssh

    - name: Install ssh key
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: 0600
      tags:
        - ssh

    - name: Install public ssh key
      copy:
        src: "{{ source_key }}.pub"
        dest: "{{ dest_key }}.pub"
        mode: 0644
      tags:
        - ssh

    - name: load ssh key
      shell: ssh-add ~/.ssh/id_ed25519
      tags:
        - ssh

    - name: Ensure repo is up-to-date
      ansible.builtin.git:
        repo: git@github.com:Naf256/hello.git
        dest: ~/hello


