- hosts: localhost
  become_method: su
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
  tasks:
    - name: Change shell
      ansible.builtin.include_tasks: tasks/zsh.yml
