- name: setting up email in git
  git_config:
    name: user.email
    scope: global
    value: "nafis_256@yahoo.com"
  tags:
    - git-personal
- name: setting up name in git
  git_config:
    name: user.name
    scope: global
    value: "tokyaramen"
  tags:
    - git-personal
