- name: Downloading go package
  apt:
    name: ["wget", "tar"]
  shell: wget https://go.dev/dl/go1.21.0.linux-amd64.tar.gz && rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz
  tags:
    - install
    - go

- name: Setting up go path
  shell: echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.profile
  tags:
    - install
    - go
