- name: Add neovim unstable repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  tags:
    - install
    - productivity

- name: Install packages
  become: true
  apt:
    name: [ "tmux", "neovim", "vlc", "firefox", "wireshark", "fzf", "gimp", "xclip", "screenkey", "ripgrep", "shutter" ]
  tags:
    - install
    - productivity
