- name: Install zsh
  apt: name=zsh
  tags:
    - zsh
- name: Change shell
  shell: chsh -s $(which zsh) tokyaramen
  tags:
    - zsh
# - name: Install oh-my-zsh
#   shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
#   environment:
#     ZSH: "/home/tokyaramen/.oh-my-zsh"
#     RUNZSH: "no"
#     KEEP_ZSHRC: "yes"
#   tags:
#     - zsh
- name: Install zsh plugin autosuggestion
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "/home/tokyaramen/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - zsh
- name: update our zshrc
  shell: sed -i 's/(git/(git zsh-autosuggestions/' /home/tokyaramen/.zshrc
  tags:
    - zsh
